### ISSUE TITLE
NoMethodError method 'first' is not defined

### ISSUE THREAD

**Issue by float3** [drewbaumann/gpt3-recipe-builder#1]
```
gpt3-recipe-builder/lib/recipe_story.rb:12:in `generate': undefined method `first' for nil:NilClass (NoMethodError)
	from recipe_generator.rb:33:in `recipe_story'
	from recipe_generator.rb:20:in `display'
	from recipe_generator.rb:15:in `run'
	from recipe_generator.rb:37:in `<main>'
```

**Comment by float3** [comment]
The Issue was a broken key in the .env file.
I ended up having to make a new account because all keys from that OpenAI account were broken

**Comment by shawndegroot** [comment]
Having similar issue: 
lib/recipe.rb:19:in `generate': undefined method `first' for nil:NilClass (NoMethodError)

    ).dig("choices").first.dig("text")
                    ^^^^^^
	from (irb):3:in `<main>'
	from /Users/shawndegroot/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
	from /Users/shawndegroot/.rbenv/versions/3.2.0/bin/irb:25:in `load'
	from /Users/shawndegroot/.rbenv/versions/3.2.0/bin/irb:25:in `<main>'
